FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

ARG PORT DB_URL DB_USER MAILCHIMP_URL MAILCHIMP_API_KEY MAILCHIMP_LIST_ID

ENV PORT=${PORT}
ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV MAILCHIMP_URL=${MAILCHIMP_URL}
ENV MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
ENV MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID}

COPY target/in-the-know-yyc-api.jar in-the-know-yyc-api.jar
CMD ["java","-jar","in-the-know-yyc-api.jar"]
